version: '3'

services:

  mysql:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  amqp:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
