# Routes
get-user:
  path: /users/{uid}
  controller: App\Controller\GetUserController
  methods:
    - GET

put-user:
  path: /users/{uid}
  controller: App\Controller\PutUserController
  methods:
    - PUT

delete-user:
  path: /users/{uid}
  controller: App\Controller\DeleteUserController
  methods:
    - DELETE
